const imageModelOptions = {
  "ideogram-v3": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    custom_inputs: [
      {
        id: "renderingSpeed",
        type: "select",
        label: "Rendering Speed",
        options: ["TURBO", "BALANCED", "QUALITY"],
        default: "BALANCED",
      },
      {
        id: "colorPalette",
        type: "text",
        label: "Color Palette Name",
        placeholder: "e.g. vibrant",
      },
      {
        id: "styleCodes",
        type: "text",
        label: "Style Codes (comma-separated)",
        placeholder: "e.g. abcd1234, efgh5678",
      },
      {
        id: "style",
        type: "select",
        label: "Style",
        options: ["AUTO", "GENERAL", "REALISTIC", "DESIGN"],
      },
      {
        id: "expandPrompt",
        type: "checkbox",
        label: "Use MagicPrompt (Expand Prompt)",
        default: true,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 12345",
      },
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. blurry, low quality",
      },
    ],
  },

  "hidream-i1-dev": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    custom_inputs: [
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. blurry, low quality",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Inference Steps",
        default: 28,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 42",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode (Wait for response)",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpeg", "png"],
        default: "jpeg",
      },
    ],
  },
  "hidream-i1-full": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    custom_inputs: [
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. blurry, low quality",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Inference Steps",
        default: 30,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 42",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode (Wait for response)",
        default: true,
      },

      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpeg", "png"],
        default: "jpeg",
      },
    ],
  },
  "hidream-i1-fast": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    custom_inputs: [
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. blurry, low quality",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Inference Steps",
        default: 16, // Optimized for speed
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 42",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode (Wait for response)",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpeg", "png"],
        default: "jpeg",
      },
    ],
  },
  "recraft-v3": {
    providers: ["auto", "fal", "replicate"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    custom_inputs: [
      {
        id: "style",
        type: "select",
        label: "Style",
        options: [
          "any",
          "realistic_image",
          "digital_illustration",
          "digital_illustration/pixel_art",
          "digital_illustration/hand_drawn",
          "digital_illustration/grain",
          "digital_illustration/infantile_sketch",
          "digital_illustration/2d_art_poster",
          "digital_illustration/handmade_3d",
          "digital_illustration/hand_drawn_outline",
          "digital_illustration/engraving_color",
          "digital_illustration/2d_art_poster_2",
          "realistic_image/b_and_w",
          "realistic_image/hard_flash",
          "realistic_image/hdr",
          "realistic_image/natural_light",
          "realistic_image/studio_portrait",
          "realistic_image/enterprise",
          "realistic_image/motion_blur",
        ],
        default: "realistic_image/studio_portrait",
      },
      {
        id: "styleId",
        type: "text",
        label: "Style ID",
        default: "",
        placeholder: "Optional",
      },
      {
        id: "colors",
        type: "text",
        label: "Colors (comma-separated RGB)",
        placeholder: "e.g. 255,0,0; 0,255,0",
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
    ],
  },

  fooocus: {
    providers: ["auto", "fal"],
    aspect_ratios: ["1024x1024", "1280x720", "1920x1080"],
    custom_inputs: [
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. blurry, bad anatomy",
      },
      {
        id: "styles",
        type: "text",
        label: "Styles (comma-separated)",
        placeholder: "e.g. Fooocus Enhance,Fooocus Sharp",
      },
      {
        id: "performance",
        type: "select",
        label: "Performance",
        options: ["Speed", "Quality", "Extreme Speed", "Lightning"],
        default: "Extreme Speed",
      },
      {
        id: "guidanceScale",
        type: "number",
        label: "Guidance Scale",
        default: 4.0,
      },
      {
        id: "sharpness",
        type: "number",
        label: "Sharpness",
        default: 2.0,
      },
      {
        id: "refinerModel",
        type: "select",
        label: "Refiner Model",
        options: ["None", "realisticVisionV60B1_v51VAE.safetensors"],
        default: "None",
      },
      {
        id: "refinerSwitch",
        type: "number",
        label: "Refiner Switch Point",
        default: 0.8,
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpeg", "png", "webp"],
        default: "jpeg",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
    ],
  },

  "black-forest-labs-flux-1-1-pro": {
    providers: ["auto", "fal", "deepinfra"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    provider_aspect_ratios: {
      fal: {
        square_hd: null,
        square: null,
        portrait_4_3: null,
        portrait_16_9: null,
        landscape_4_3: null,
        landscape_16_9: null,
      },
      deepinfra: [
        "1024x448",
        "1024x576",
        "1024x768",
        "1024x688",
        "1024x1024",
        "688x1024",
        "768x1024",
        "576x1024",
        "448x1024",
      ],
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpeg", "png"],
        default: "jpeg",
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
  },
  "black-forest-labs-flux-kontext-pro": {
    providers: ["auto", "replicate"],
    aspect_ratios: {
      "1:1": "1:1",
      "16:9": "16:9",
      "9:16": "9:16",
      "4:3": "4:3",
      "3:4": "3:4",
      "3:2": "3:2",
      "2:3": "2:3",
      "4:5": "4:5",
      "5:4": "5:4",
      "21:9": "21:9",
      "9:21": "9:21",
      "2:1": "2:1",
      "1:2": "1:2",
    },
    provider_aspect_ratios: {
      replicate: {
        "1:1": "1:1",
        "16:9": "16:9",
        "9:16": "9:16",
        "4:3": "4:3",
        "3:4": "3:4",
        "3:2": "3:2",
        "2:3": "2:3",
        "4:5": "4:5",
        "5:4": "5:4",
        "21:9": "21:9",
        "9:21": "9:21",
        "2:1": "2:1",
        "1:2": "1:2",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpg", "png"],
        default: "jpg",
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["replicate"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "replicate",
    },
  },
  "black-forest-labs-flux-kontext-max": {
    providers: ["auto", "replicate"],
    aspect_ratios: {
      "1:1": "1:1",
      "16:9": "16:9",
      "9:16": "9:16",
      "4:3": "4:3",
      "3:4": "3:4",
      "3:2": "3:2",
      "2:3": "2:3",
      "4:5": "4:5",
      "5:4": "5:4",
      "21:9": "21:9",
      "9:21": "9:21",
      "2:1": "2:1",
      "1:2": "1:2",
    },
    provider_aspect_ratios: {
      replicate: {
        "1:1": "1:1",
        "16:9": "16:9",
        "9:16": "9:16",
        "4:3": "4:3",
        "3:4": "3:4",
        "3:2": "3:2",
        "2:3": "2:3",
        "4:5": "4:5",
        "5:4": "5:4",
        "21:9": "21:9",
        "9:21": "9:21",
        "2:1": "2:1",
        "1:2": "1:2",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpg", "png"],
        default: "jpg",
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["replicate"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "replicate",
    },
  },
  "black-forest-labs-flux-1.1-pro-ultra": {
    providers: ["auto", "replicate"],
    aspect_ratios: {
      "21:9": "21:9",
      "16:9": "16:9",
      "3:2": "3:2",
      "4:3": "4:3",
      "5:4": "5:4",
      "1:1": "1:1",
      "4:5": "4:5",
      "3:4": "3:4",
      "2:3": "2:3",
      "9:16": "9:16",
      "9:21": "9:21",
    },
    provider_aspect_ratios: {
      replicate: {
        "21:9": "21:9",
        "16:9": "16:9",
        "3:2": "3:2",
        "4:3": "4:3",
        "5:4": "5:4",
        "1:1": "1:1",
        "4:5": "4:5",
        "3:4": "3:4",
        "2:3": "2:3",
        "9:16": "9:16",
        "9:21": "9:21",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 987654",
        description: "Random seed for reproducibility",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpg", "png"],
        default: "jpg",
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Mode",
        default: false,
        description: "Choose 'raw' for realism, 'ultra' for enhanced visuals",
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["replicate"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "replicate",
    },
  },
  "bytedance-sdxl-lightning-4step": {
    providers: ["auto", "replicate"],
    aspect_ratios: {
      "1:1": "1:1",
      "16:9": "16:9",
      "9:16": "9:16",
      "4:3": "4:3",
      "3:4": "3:4",
      "3:2": "3:2",
      "2:3": "2:3",
      "4:5": "4:5",
      "5:4": "5:4",
      "21:9": "21:9",
      "9:21": "9:21",
      "2:1": "2:1",
      "1:2": "1:2",
    },
    provider_aspect_ratios: {
      replicate: {
        "1:1": "1:1",
        "16:9": "16:9",
        "9:16": "9:16",
        "4:3": "4:3",
        "3:4": "3:4",
        "3:2": "3:2",
        "2:3": "2:3",
        "4:5": "4:5",
        "5:4": "5:4",
        "21:9": "21:9",
        "9:21": "9:21",
        "2:1": "2:1",
        "1:2": "1:2",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Set a random seed for reproducibility",
      },
      {
        id: "guidanceScale",
        type: "number",
        label: "Guidance Scale",
        placeholder: "e.g. 0",
        default: 0,
      },
      {
        id: "negativePrompt",
        type: "text",
        label: "Negative Prompt",
        placeholder: "e.g. worst quality, low quality",
        default: "worst quality, low quality",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Inference Steps",
        placeholder: "e.g. 4",
        default: 4,
      },
      {
        id: "scheduler",
        type: "select",
        label: "Scheduler",
        options: [
          "DDIM",
          "DPMSolverMultistep",
          "HeunDiscrete",
          "KarrasDPM",
          "K_EULER_ANCESTRAL",
          "K_EULER",
          "PNDM",
          "DPM++2MSDE",
        ],
        default: "K_EULER",
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["jpg", "png"],
        default: "jpg",
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["replicate"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "replicate",
    },
  },

  "stabilityai-sd3-5": {
    providers: ["deepinfra", "auto"],
    aspect_ratios: {
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    provider_aspect_ratios: {
      deepinfra: {
        square_hd: "1024x1024",
        square: "768x768",
        portrait_4_3: "768x1024",
        portrait_16_9: "576x1024",
        landscape_4_3: "1024x768",
        landscape_16_9: "1024x576",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["1", "0.25"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 4,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["deepinfra"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "deepinfra",
    },
  },
  "stabilityai-sd3-5-medium": {
    providers: ["auto", "deepinfra"],
    aspect_ratios: {
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    provider_aspect_ratios: {
      deepinfra: {
        square_hd: "1024x1024",
        square: "768x768",
        portrait_4_3: "768x1024",
        portrait_16_9: "576x1024",
        landscape_4_3: "1024x768",
        landscape_16_9: "1024x576",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 987654",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["2", "1", "0.25"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 4,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["deepinfra"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "deepinfra",
    },
  },
  "stabilityai-sdxl-turbo": {
    providers: ["auto", "deepinfra"],
    aspect_ratios: {
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    provider_aspect_ratios: {
      deepinfra: {
        square_hd: "1024x1024",
        square: "768x768",
        portrait_4_3: "768x1024",
        portrait_16_9: "576x1024",
        landscape_4_3: "1024x768",
        landscape_16_9: "1024x576",
      },
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["1", "0.5"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 2,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["deepinfra"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "deepinfra",
    },
  },
  "black-forest-labs-flux-1-dev": {
    providers: ["auto", "together"],
    aspect_ratios: {
      // Default aspect ratios (used when provider is 'auto')
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    // Provider-specific aspect ratios
    provider_aspect_ratios: {
      fal: {
        square_hd: "1024x1024",
        square: "768x768",
        portrait_4_3: "768x1024",
        portrait_16_9: "576x1024",
        landscape_4_3: "1024x768",
        landscape_16_9: "1024x576",
      },
      replicate: {
        "1:1": "1:1",
        "16:9": "16:9",
        "21:9": "21:9",
        "3:2": "3:2",
        "2:3": "2:3",
        "4:5": "4:5",
        "5:4": "5:4",
        "3:4": "3:4",
        "4:3": "4:3",
        "9:16": "9:16",
        "9:21": "9:21",
      },
      together: {
        "1:1": "1:1",
        "16:9": "16:9",
        "21:9": "21:9",
        "4:3": "4:3",
        "9:16": "9:16",
      },
    },
    // UI input schema
    custom_inputs: [
      {
        id: "prompt",
        type: "textarea",
        label: "Prompt",
        placeholder: "Describe the image you want to generate",
        required: true,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },

      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["1", "0.25"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 4,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    // Add this configuration to control UI display
    ui_config: {
      always_show_output_settings: true, // Always show output settings container
      show_custom_inputs_for: ["fal", "replicate"], // Show custom inputs for these providers
      hide_custom_inputs_for: ["auto"], // Hide custom inputs for these providers
      default_provider: "auto", // Default selected provider
    },
  },
  "black-forest-labs-flux-schnell": {
    providers: ["auto", "fal", "replicate", "together"],
    aspect_ratios: {
      // Default aspect ratios (used when provider is 'auto')
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    // Provider-specific aspect ratios
    provider_aspect_ratios: {
      fal: {
        square_hd: "1024x1024",
        square: "768x768",
        portrait_4_3: "768x1024",
        portrait_16_9: "576x1024",
        landscape_4_3: "1024x768",
        landscape_16_9: "1024x576",
      },
      replicate: {
        "1:1": "1:1",
        "16:9": "16:9",
        "21:9": "21:9",
        "3:2": "3:2",
        "2:3": "2:3",
        "4:5": "4:5",
        "5:4": "5:4",
        "3:4": "3:4",
        "4:3": "4:3",
        "9:16": "9:16",
        "9:21": "9:21",
      },
      together: {
        "1:1": "1:1",
        "16:9": "16:9",
        "21:9": "21:9",
        "4:3": "4:3",
        "9:16": "9:16",
      },
    },
    // UI input schema
    custom_inputs: [
      {
        id: "prompt",
        type: "textarea",
        label: "Prompt",
        placeholder: "Describe the image you want to generate",
        required: true,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["1", "0.25"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 4,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    // Add this configuration to control UI display
    ui_config: {
      always_show_output_settings: true, // Always show output settings container
      show_custom_inputs_for: ["fal", "replicate"], // Show custom inputs for these providers
      hide_custom_inputs_for: ["auto"], // Hide custom inputs for these providers
      default_provider: "auto", // Default selected provider
    },
  },
  "black-forest-labs-flux-pro": {
    providers: ["auto", "deepinfra"],
    aspect_ratios: {
      square_hd: "1024x1024",
      square: "768x768",
      portrait_4_3: "768x1024",
      portrait_16_9: "576x1024",
      landscape_4_3: "1024x768",
      landscape_16_9: "1024x576",
    },
    provider_aspect_ratios: {
      deepinfra: {
        "1:1": "1:1",
        "4:3": "4:3",
        "16:9": "16:9",
        "3:2": "3:2",
        "2:3": "2:3",
        "9:16": "9:16",
      },
    },
    custom_inputs: [
      {
        id: "prompt",
        type: "textarea",
        label: "Prompt",
        placeholder: "Describe the image you want to generate",
        required: true,
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 123456",
        description: "Random seed. Set for reproducible generation",
      },
      {
        id: "syncMode",
        type: "checkbox",
        label: "Sync Mode",
        default: true,
      },
      {
        id: "enableSafetyInput",
        type: "checkbox",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "safetyTolerance",
        type: "select",
        label: "Safety Tolerance",
        options: ["1", "2", "3", "4", "5", "6"],
        default: "2",
      },
      {
        id: "outputFormat",
        type: "select",
        label: "Output Format",
        options: ["webp", "jpg", "png"],
        default: "webp",
      },
      {
        id: "outputQuality",
        type: "number",
        label: "Output Quality",
        default: 80,
        min: 0,
        max: 100,
        description: "Only relevant for non-PNG outputs",
      },
      {
        id: "megapixels",
        type: "select",
        label: "Megapixels",
        options: ["1", "0.25"],
        default: "1",
      },
      {
        id: "numInferenceSteps",
        type: "number",
        label: "Number of Inference Steps",
        default: 4,
        min: 1,
        max: 4,
      },
      {
        id: "goFast",
        type: "checkbox",
        label: "Go Fast Mode",
        default: true,
      },
      {
        id: "rawMode",
        type: "checkbox",
        label: "Raw Image (less processed)",
        default: false,
      },
    ],
    ui_config: {
      always_show_output_settings: true,
      show_custom_inputs_for: ["deepinfra"],
      hide_custom_inputs_for: ["auto"],
      default_provider: "deepinfra",
    },
  },
  bagel: {
    providers: ["fal", "auto"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    provider_aspect_ratios: {
      fal: ["1024x1024"],
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
      },
    ],
  },
  "imagen4-preview": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      "1: 1": null,
      " 16: 9": null,
      "9: 16": null,
      "3: 4": null,
      "4: 3": null,
    },
    provider_aspect_ratios: {
      fal: ["1024x1024"],
    },
    custom_inputs: [
      {
        id: "negativePromptInput",
        type: "text",
        label: "Negative Prompt",
        placeholder: "What to discourage in the generated images (optional)",
        default: "",
      },
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
      },
    ],
  },
  "f-lite-standard": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    provider_aspect_ratios: {
      fal: ["1024x1024"],
    },
    custom_inputs: [
      {
        id: "seedInput",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
      },
      {
        id: "negative_prompt",
        type: "text",
        label: "Negative Prompt",
        placeholder: "What to avoid in the image",
      },
      {
        id: "num_inference_steps",
        type: "number",
        label: "Inference Steps",
        placeholder: "e.g. 28",
        default: 28,
      },
      {
        id: "guidance_scale",
        type: "number",
        label: "Guidance Scale",
        placeholder: "e.g. 3.5",
        default: 3.5,
      },
      {
        id: "sync_mode",
        type: "boolean",
        label: "Sync Mode",
        default: false,
      },
      {
        id: "num_images",
        type: "number",
        label: "Number of Images",
        placeholder: "e.g. 1",
        default: 1,
      },
      {
        id: "enable_safety_checker",
        type: "boolean",
        label: "Enable Safety Checker",
        default: true,
      },
    ],
  },
  "sana-v1.5-4.8b": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      square_hd: null,
      square: null,
      portrait_4_3: null,
      portrait_16_9: null,
      landscape_4_3: null,
      landscape_16_9: null,
    },
    provider_aspect_ratios: {
      fal: ["1024x1024"],
    },
    custom_inputs: [
      {
        id: "seed",
        type: "number",
        label: "Seed",
        placeholder: "e.g. 777888",
      },
      {
        id: "negative_prompt",
        type: "text",
        label: "Negative Prompt",
        placeholder: "What to avoid in the image",
      },
      {
        id: "num_inference_steps",
        type: "number",
        label: "Inference Steps",
        placeholder: "e.g. 18",
        default: 18,
      },
      {
        id: "guidance_scale",
        type: "number",
        label: "Guidance Scale",
        placeholder: "e.g. 5",
        default: 5,
      },
      {
        id: "sync_mode",
        type: "boolean",
        label: "Sync Mode",
        default: false,
      },
      {
        id: "num_images",
        type: "number",
        label: "Number of Images",
        placeholder: "e.g. 1",
        default: 1,
      },
      {
        id: "enable_safety_checker",
        type: "boolean",
        label: "Enable Safety Checker",
        default: true,
      },
      {
        id: "output_format",
        type: "select",
        label: "Output Format",
        default: "jpeg",
        options: ["jpeg", "png"],
      },
      {
        id: "style_name",
        type: "select",
        label: "Style",
        default: "(No style)",
        options: [
          "(No style)",
          "Cinematic",
          "Photographic",
          "Anime",
          "Manga",
          "Digital Art",
          "Pixel art",
          "Fantasy art",
          "Neonpunk",
          "3D Model",
        ],
      },
    ],
  },
  "minimax-image-01": {
    providers: ["auto", "fal"],
    aspect_ratios: {
      "1:1": null,
      "16:9": null,
      "4:3": null,
      "3:2": null,
      "2:3": null,
      "3:4": null,
      "9:16": null,
      "21:9": null,
    },
    provider_aspect_ratios: {
      fal: ["1:1", "16:9", "4:3", "3:2", "2:3", "3:4", "9:16", "21:9"],
    },
    custom_inputs: [],
  },
};

const imageModelCredits = {
  "black-forest-labs-flux-1-1-pro": 5, // fal: 5
  "black-forest-labs-flux-schnell": 7, // fal: 7
  "black-forest-labs-flux-1-dev": 4, // together: 4
  "black-forest-labs-flux-pro": 5, // base64: 4 (but you had 5 in your example)
  "black-forest-labs-flux-kontext-pro": 4, // replicate: 4
  "black-forest-labs-flux-kontext-max": 7, // replicate: 7
  "black-forest-labs-flux-1.1-pro-ultra": 7, // replicate: 7
  "bytedance-sdxl-lightning-4step": 7, // replicate: 7
  "stabilityai-sd3-5": 4, // base64: 4
  "stabilityai-sd3-5-medium": 4, // base64: 4
  "stabilityai-sdxl-turbo": 4, // base64: 4
  "recraft-v3": 4, // fal: 4
  fooocus: 3, // fal: 3
  "hidream-i1-dev": 4, // fal: 4
  "hidream-i1-full": 6, // fal: 6
  "hidream-i1-fast": 6, // fal: 6
  "ideogram-v3": 7, // fal: 7
  bagel: 10, // fal: 10
  "imagen4-preview": 12, // fal: 12
  "f-lite-standard": 12, // fal: 12
  "sana-v1.5-4.8b": 12, // fal: 12
  "minimax-image-01": 12, // fal: 12
};
